spring.application.name=Sergio Robla
spring.profiles.active=dev

# Configuración del controlador para MySQL
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Dialecto de Hibernate para MySQL
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# Mostrar las consultas SQL en la consola
spring.jpa.show-sql=true

# Permite crear tablas en la BBDD
#spring.jpa.hibernate.ddl-auto=create

# Permite actualizar tablas en la BBDD
spring.jpa.hibernate.ddl-auto=update